---
- hosts: dev
  remote_user: ec2-user
- name: Install Oracle Java 8
    become: yes
    yum: 
      name: ['java-1.8.0-openjdk'] 
      state: latest
  
  - name: "Copy jar application"
    copy:
      src: "target/lab-cicd-0.0.1-SNAPSHOT.jar"
      dest: "./lab-cicd-0.0.1-SNAPSHOT.jar"
      mode: "u+x"

  - name: Run Spring Boot
    shell: nohup java -jar lab-cicd-0.0.1-SNAPSHOT.jar --server.port=8080 &
