---
- hosts: bkend_dev
  remote_user: ubuntu
  tasks:
  - name: Add Oracle Java Repository
    become: yes
    apt_repository: repo='ppa:openjdk-r/ppa'

  - name: Install Oracle Java 8
    become: yes
    apt: 
      name: ['openjdk-8-jdk'] 
      state: latest
  
  - name: "Copy jar application"
    copy:
      src: "lab-cicd-0.0.1-SNAPSHOT.jar"
      dest: "./lab-cicd-0.0.1-SNAPSHOT.jar"
      mode: "u+x"

  - name: Run Spring Boot
    shell: nohup java -jar lab-cicd-0.0.1-SNAPSHOT.jar --server.port=80 &
